config/routes.rb
Rails.application.routes.draw do
  get "users/show"
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  authenticated :user do
    root to: 'articles#index', as: :authenticated_root
  end

  unauthenticated do
    devise_scope :user do
      root to: 'users/registrations#new', as: :unauthenticated_root
    end
  end

  resources :articles do
    resources :comments, only: [:create, :destroy]
    resource :like, only: [:create]
  end
  
  get '/profile', to: 'users#show', as: 'user_profile'
  
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

    def create
      @article = Article.find(params[:article_id])
      @comment = @article.comments.build(comment_params)
      @comment.user = current_user 
    
      if @comment.save
        redirect_to @article, notice: "Comment posted successfully."
      else
        render "articles/show"
      end
    end
  
    def destroy
      @article = Article.find(params[:article_id])
      @comment = @article.comments.find(params[:id])
      authorize @comment
      if @comment.destroy
        redirect_to article_path(@article), notice: "Comment deleted."
      else
        redirect_to article_path(@article), alert: "Failed to delete comment."
      end
    end
  
    private
  
    def comment_params
      params.require(:comment).permit(:body)
    end    
  end
  

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="card mb-2">
  <div class="card-body d-flex justify-content-between align-items-start">
    <div>
      <% if comment.user.avatar.attached? %>
        <%= image_tag url_for(comment.user.avatar), width: 50, height: 50, class: "rounded me-2" %>
      <% end %>

      <strong><%= comment.user.username %></strong>
      <p class="mb-0"><%= comment.body %></p>
    </div>

    <% if policy(comment).destroy? %>
    <%= button_to "🗑️", article_comment_path(@article, comment), method: :delete %>
    <% end %>
  </div>
</div>